//! Backtest request/response types and internal domain models for the backtest subsystem.
//!
//! Defines the API-facing types ([`BacktestRunRequest`], [`BacktestResultResponse`], etc.)
//! and the internal engine types ([`Kline`], [`Signal`], [`Account`], [`Position`])
//! used during backtest execution.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

// ============ Request Types ============

/// Request body for POST /api/v1/backtest — submit a new backtest run.
#[derive(Debug, Deserialize)]
pub struct BacktestRunRequest {
    pub strategy_id: Uuid,
    pub config: BacktestConfig,
}

/// Backtest configuration: symbol, date range, capital, and fee parameters.
#[derive(Debug, Deserialize, Serialize, Clone, Default)]
pub struct BacktestConfig {
    pub symbol: String,
    pub interval: String,
    pub start_date: String, // "2024-01-01"
    pub end_date: String,   // "2024-12-31"
    pub initial_capital: f64,
    #[serde(default = "default_fee_rate")]
    pub fee_rate: f64,
    #[serde(default = "default_slippage_rate")]
    pub slippage_rate: f64,
    /// Price limit percentage for backtest (e.g. 0.10 = 10% limit).
    /// Set to None or 0.0 to disable price limit enforcement.
    #[serde(default)]
    pub price_limit_pct: Option<f64>,
}

fn default_fee_rate() -> f64 {
    0.001
}
fn default_slippage_rate() -> f64 {
    0.0005
}

// ============ Response Types ============

/// Immediate response after submitting a backtest run (status=running).
#[derive(Debug, Serialize)]
pub struct BacktestRunResponse {
    pub id: Uuid,
    pub status: String,
    pub progress: i32,
    pub created_at: DateTime<Utc>,
}

/// Full backtest result including config, metrics, trades, and equity curve.
///
/// Returned by GET /api/v1/backtest/{id}.
#[derive(Debug, Serialize)]
pub struct BacktestResultResponse {
    pub id: Uuid,
    pub user_id: Uuid,
    pub strategy_id: Uuid,
    pub status: String,
    pub progress: i32,
    pub config: BacktestConfig,
    pub metrics: Option<BacktestMetrics>,
    pub trades: Option<Vec<TradeRecord>>,
    pub equity_curve: Option<Vec<EquityPoint>>,
    pub start_time: Option<DateTime<Utc>>,
    pub end_time: Option<DateTime<Utc>>,
    pub duration_ms: Option<i64>,
    pub error: Option<String>,
}

/// Backtest progress response (used by polling API).
#[derive(Debug, Serialize)]
pub struct BacktestProgressResponse {
    pub id: Uuid,
    pub status: String,
    pub progress: i32,
    pub current_bar: i64,
    pub total_bars: i64,
    pub elapsed_ms: i64,
}

/// Summary of a backtest run for list views.
#[derive(Debug, Serialize)]
pub struct BacktestSummary {
    pub id: Uuid,
    pub status: String,
    pub config: BacktestConfig,
    pub metrics: Option<MetricsPreview>,
    pub start_time: Option<DateTime<Utc>>,
    pub duration_ms: Option<i64>,
    pub created_at: DateTime<Utc>,
}

/// Condensed metrics preview for list views (top 4 KPIs).
#[derive(Debug, Serialize)]
pub struct MetricsPreview {
    pub total_return_pct: f64,
    pub sharpe_ratio: f64,
    pub max_drawdown_pct: f64,
    pub total_trades: i32,
}

// ============ Internal Types ============

/// A single OHLCV bar used by the backtest engine.
#[derive(Debug, Clone, Copy)]
pub struct Kline {
    pub open_time: i64, // ms
    pub open: f64,
    pub high: f64,
    pub low: f64,
    pub close: f64,
    pub volume: f64,
}

/// Trading signal generated by a strategy template.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Signal {
    Buy { quantity_pct: f64 }, // 0.0 ..= 1.0
    Sell { quantity_pct: f64 },
    CloseAll,
    Hold,
}

/// Position direction: long (buy) or short (sell).
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Direction {
    Long,
    Short,
}

/// Simulated account tracking cash and equity.
#[derive(Debug, Clone)]
pub struct Account {
    pub initial_capital: f64,
    pub cash: f64,
    pub equity: f64,
}

/// An open position with entry details and accumulated costs.
#[derive(Debug, Clone)]
pub struct Position {
    pub direction: Direction,
    pub quantity: f64,
    pub entry_price: f64,
    pub entry_time: i64,
    pub stop_loss: Option<f64>,
    pub take_profit: Option<f64>,
    pub fee_paid: f64,
    pub slippage_paid: f64,
    /// Limit type applied at entry (upper/lower), if any.
    pub limit_type: Option<LimitType>,
}

/// Price limit type for backtest price limit enforcement.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum LimitType {
    #[serde(rename = "upper")]
    Upper, // 涨停
    #[serde(rename = "lower")]
    Lower, // 跌停
}

/// A completed trade record with entry/exit details and PnL.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TradeRecord {
    pub entry_time: i64,
    pub exit_time: i64,
    pub direction: String, // "long" | "short"
    pub entry_price: f64,
    pub exit_price: f64,
    pub quantity: f64,
    pub pnl_usdt: f64,
    pub pnl_pct: f64,
    pub holding_period_ms: i64,
    pub exit_reason: String, // "signal" | "stop_loss" | "take_profit" | "liquidation" | "limit_hit"
    pub fee: f64,
    pub slippage: f64,
    /// Whether the trade hit the price limit (upward or downward limit).
    #[serde(default)]
    pub hit_limit: bool,
    /// The type of limit that was hit, if any.
    pub limit_type: Option<LimitType>,
}

/// A single point on the equity curve with drawdown percentage.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EquityPoint {
    pub time: i64,
    pub equity: f64,
    pub drawdown_pct: f64,
}

/// Comprehensive backtest performance metrics.
///
/// Covers return, risk-adjusted ratios (Sharpe/Sortino/Calmar/Alpha/Beta/Information),
/// drawdown, win rate, profit factor, expectancy, Kelly fraction, turnover, and cost metrics.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BacktestMetrics {
    pub total_return_pct: f64,
    pub annualized_return_pct: f64,
    pub max_drawdown_pct: f64,
    pub sharpe_ratio: f64,
    pub sortino_ratio: f64,
    pub calmar_ratio: f64,
    pub win_rate: f64,
    pub total_trades: i32,
    pub profit_factor: f64,
    pub avg_win_pct: f64,
    pub avg_loss_pct: f64,
    pub avg_trade_pct: f64,
    pub total_fees: f64,
    pub total_slippage: f64,
    // ===== P2-2: 8 new metrics =====
    /// Jensen's alpha: (strategy_return - beta * benchmark_return) annualized.
    /// Measures risk-adjusted excess return vs BTC benchmark. `0.0` when benchmark
    /// data is unavailable.
    pub alpha: f64,
    /// Beta: covariance(strategy_returns, btc_returns) / variance(btc_returns).
    /// Sensitivity to BTC market movements. `0.0` when benchmark data is unavailable.
    pub beta: f64,
    /// Information Ratio: (strategy_return - benchmark_return) / tracking_error.
    /// Risk-adjusted active return vs benchmark. `0.0` when benchmark data is unavailable.
    pub information_ratio: f64,
    /// Kelly fraction in percent: W - (1 - W) / R, where W = win_rate and R = win/loss ratio.
    /// Theoretical optimal position size for maximizing log-growth. Clamped to [-100, 100].
    /// `0.0` when no trades.
    pub kelly_pct: f64,
    /// Expectancy per trade: (win_rate * avg_win) - (loss_rate * avg_loss) in percent.
    /// Expected PnL per trade; positive means profitable in the long run.
    /// `0.0` when no trades.
    pub expectancy: f64,
    /// Portfolio turnover: sum(abs(trade_value)) / average_equity / period_days.
    /// Measures trading activity. `0.0` when no trades or zero average equity.
    pub turnover: f64,
    /// Estimated average slippage per trade in USDT (already accumulated in
    /// trades, exposed separately for cost analysis). Mirrors the average of
    /// `TradeRecord::slippage` over the trade set; `0.0` when no trades.
    pub slippage_estimation: f64,
    /// Number of days to recover from the maximum drawdown trough to a new equity
    /// peak after the trough. `0` when no drawdown or already recovered.
    pub drawdown_recovery_days: i64,
}

// ============ Validation ============

impl BacktestConfig {
    pub fn validate(&self) -> Result<(), String> {
        // Parse dates
        let start = chrono::NaiveDate::parse_from_str(&self.start_date, "%Y-%m-%d")
            .map_err(|_| "start_date must be YYYY-MM-DD".to_string())?;
        let end = chrono::NaiveDate::parse_from_str(&self.end_date, "%Y-%m-%d")
            .map_err(|_| "end_date must be YYYY-MM-DD".to_string())?;

        if start >= end {
            return Err("start_date must be before end_date".into());
        }

        let days = (end - start).num_days();
        if days < 7 {
            return Err("date range must be at least 7 days".into());
        }

        if self.initial_capital < 100.0 {
            return Err("initial_capital must be >= 100".into());
        }

        if !(0.0..=0.01).contains(&self.fee_rate) {
            return Err("fee_rate must be 0..0.01".into());
        }

        if !(0.0..=0.01).contains(&self.slippage_rate) {
            return Err("slippage_rate must be 0..0.01".into());
        }

        if let Some(pct) = self.price_limit_pct
            && !(0.0..=0.5).contains(&pct)
        {
            return Err("price_limit_pct must be 0..0.5".into());
        }

        Ok(())
    }
}
