/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/feature-flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /api/v1/admin/feature-flags`
         * @description Admin list: every flag row (raw, no per-user evaluation). The admin
         *     UI reads this to populate the toggle table.
         */
        get: operations["feature_flags_admin_list"];
        put?: never;
        /**
         * `POST /api/v1/admin/feature-flags`
         * @description Admin upsert: create or update a flag row by `key`. The response is
         *     the persisted row. The cache is invalidated automatically by
         *     `svc::upsert`.
         */
        post: operations["feature_flags_admin_upsert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/feature-flags/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * `DELETE /api/v1/admin/feature-flags/{key}`
         * @description Admin delete. Returns 204 if a row was actually removed, 404
         *     otherwise. The cache is invalidated automatically.
         */
        delete: operations["feature_flags_admin_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /api/v1/audit-logs`
         * @description List audit log entries. All filters are optional and combine as AND.
         *     Pagination: `page` (1-indexed, default 1) / `size` (default 20, max 200).
         *
         *     Response shape: `ApiResponse<AuditLogPage>` where `AuditLogPage = { items, total, page, size }`.
         */
        get: operations["audit_logs_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit-logs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /api/v1/audit-logs/{id}`
         * @description Single audit entry by primary key. Returns 404 if not found.
         */
        get: operations["audit_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /api/v1/auth/login */
        post: operations["auth_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /api/v1/auth/logout */
        post: operations["auth_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/v1/auth/me - alias for /users/me */
        get: operations["auth_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /api/v1/auth/refresh */
        post: operations["auth_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /api/v1/auth/register */
        post: operations["auth_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/copy-trading/calculate-shares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * `POST /api/v1/copy-trading/calculate-shares` — manager/trader
         *     triggers a profit-share settlement for one subscription across the
         *     given period. Idempotent on (subscription, period_start, period_end).
         */
        post: operations["copy_trading_calculate_shares"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/copy-trading/my-subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /api/v1/copy-trading/my-subscriptions` — subscriptions the
         *     caller has as a follower.
         */
        get: operations["copy_trading_my_subscriptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/copy-trading/my-trader": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /api/v1/copy-trading/my-trader` — caller's trader profile +
         *     subscribers.
         */
        get: operations["copy_trading_my_trader"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/copy-trading/profit-shares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /api/v1/copy-trading/profit-shares` — the caller's profit-share
         *     history (as either follower or trader).
         */
        get: operations["copy_trading_profit_shares"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/copy-trading/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * `POST /api/v1/copy-trading/register` — register the caller as a
         *     copy trader.
         */
        post: operations["copy_trading_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/copy-trading/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** `POST /api/v1/copy-trading/subscribe` — subscribe to a trader. */
        post: operations["copy_trading_subscribe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/copy-trading/traders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /api/v1/copy-trading/traders` — list active traders, sorted by
         *     monthly_pnl DESC.
         */
        get: operations["copy_trading_list_traders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/copy-trading/traders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/copy-trading/traders/{id}` — trader detail. */
        get: operations["copy_trading_get_trader"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/copy-trading/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /api/v1/copy-trading/trades` — the caller's audit trail of
         *     copied trades.
         */
        get: operations["copy_trading_trades"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/copy-trading/unsubscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** `POST /api/v1/copy-trading/unsubscribe` — cancel a subscription. */
        post: operations["copy_trading_unsubscribe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feature-flags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /api/v1/feature-flags`
         * @description User bootstrap: returns the per-user evaluation of every known flag.
         *     Frontend caches this map and uses it via `useFeatureFlag(key)`. We
         *     evaluate against the *current* caller's `user_id` so the response
         *     naturally captures whitelist + percentage rollout.
         */
        get: operations["feature_flags_evaluate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe: DB 与 Redis 都可达时返回 200，否则 503。
         * @description 任何一个依赖 ping 失败就把整体标记为 unready。响应体里逐项列出结果，
         *     方便 dashboard / pagerDuty 看到具体哪个依赖挂了。
         */
        get: operations["system_readiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market/depth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/v1/market/depth — 获取深度数据 */
        get: operations["market_get_depth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market/ticker": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/v1/market/ticker — 获取单个交易对 Ticker */
        get: operations["market_get_ticker"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market/tickers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/v1/market/tickers — 获取所有交易对 Ticker */
        get: operations["market_list_tickers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pamm/funds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/pamm/funds` — list all `Active` funds. */
        get: operations["pamm_list_funds"];
        put?: never;
        /**
         * `POST /api/v1/pamm/funds` — open a new fund. The caller becomes
         *     its manager.
         */
        post: operations["pamm_create_fund"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pamm/funds/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/pamm/funds/{id}` — fund detail + current NAV. */
        get: operations["pamm_get_fund"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pamm/funds/{id}/distribute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * `POST /api/v1/pamm/funds/{id}/distribute` — manager triggers a
         *     profit distribution for the given period.
         */
        post: operations["pamm_distribute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pamm/funds/{id}/investments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /api/v1/pamm/funds/{id}/investments` — manager + self can
         *     see the investor list.
         */
        get: operations["pamm_list_fund_investments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pamm/funds/{id}/liquidate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * `POST /api/v1/pamm/funds/{id}/liquidate` — manager liquidates the
         *     fund. Returns 204 No Content on success.
         */
        post: operations["pamm_liquidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pamm/funds/{id}/redeem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** `POST /api/v1/pamm/funds/{id}/redeem` — submit a redemption. */
        post: operations["pamm_redeem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pamm/funds/{id}/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** `POST /api/v1/pamm/funds/{id}/subscribe` — submit a subscription. */
        post: operations["pamm_subscribe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pamm/my-investments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/pamm/my-investments` — the caller's investments. */
        get: operations["pamm_my_investments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user profile */
        get: operations["users_get_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change current user password */
        post: operations["users_change_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin: update user (including role) */
        post: operations["users_admin_update"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe: 进程在跑就返回 200。
         * @description 不检查任何外部依赖。即使下游 DB/Redis 全挂，liveness 仍应返回 OK，
         *     否则 k8s 会重启 Pod，而重启并不能恢复下游。
         */
        get: operations["system_liveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdminUpdateUserRequest: {
            avatar_url?: string | null;
            display_name?: string | null;
            email?: string | null;
            is_active?: boolean | null;
            /** Format: uuid */
            role_id?: string | null;
        };
        AuditLogView: {
            action: string;
            /** Format: date-time */
            created_at: string;
            diff: components["schemas"]["Value"];
            /** Format: uuid */
            id: string;
            ip_address: string;
            request_id?: string | null;
            target_id: string;
            target_type: string;
            user_agent?: string | null;
            /** Format: uuid */
            user_id?: string | null;
        };
        AuthResponseBody: {
            access_token: string;
            /** Format: int64 */
            expires_in: number;
            refresh_token: string;
            user: components["schemas"]["UserResponse"];
        };
        CalculateSharesRequest: {
            /** Format: date-time */
            period_end: string;
            /** Format: date-time */
            period_start: string;
            /** Format: uuid */
            subscription_id: string;
            trader_fee_pct?: string | null;
        };
        CalculateSharesResponse: {
            share: components["schemas"]["ProfitShareView"];
        };
        ChangePasswordRequest: {
            new_password: string;
            old_password: string;
        };
        ChangePasswordResponse: {
            message: string;
        };
        /** @description Subset of `copy_trades` row. */
        CopyTradeView: {
            /** Format: uuid */
            copied_order_id: string;
            created_at: string;
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            original_order_id?: string | null;
            price: string;
            qty: string;
            side: string;
            status: string;
            /** Format: uuid */
            subscription_id: string;
            symbol: string;
        };
        CreateFundRequest: {
            base_currency: string;
            description?: string | null;
            high_water_mark: boolean;
            /**
             * @description Annualised management fee as a fraction (0.02 = 2%). Stored as
             *     string to preserve precision (JSON Decimal round-trip).
             */
            management_fee_pct: string;
            name: string;
            /** @description Performance fee as a fraction of HWM-increment profit (0.20 = 20%). */
            performance_fee_pct: string;
            /** Format: uuid */
            strategy_id?: string | null;
        };
        CreateFundResponse: {
            fund: components["schemas"]["FundView"];
        };
        DepthLevel: {
            /** Format: double */
            price: number;
            /** Format: double */
            quantity: number;
            /** Format: double */
            total: number;
        };
        DepthResponse: {
            asks: components["schemas"]["DepthLevel"][];
            bids: components["schemas"]["DepthLevel"][];
            /** Format: int64 */
            timestamp: number;
        };
        DistributeRequest: {
            /** Format: date-time */
            period_end: string;
            /** Format: date-time */
            period_start: string;
        };
        DistributeResponse: {
            distributions: components["schemas"]["DistributionView"][];
            /** Format: date-time */
            period_end: string;
            /** Format: date-time */
            period_start: string;
        };
        /** @description Per-period distribution row exposed in the manager dashboard. */
        DistributionView: {
            distributed_at: string;
            /** Format: uuid */
            fund_id: string;
            hwm: string;
            /** Format: uuid */
            id: string;
            mgmt_fee_charged: string;
            perf_fee_charged: string;
            period_end: string;
            period_start: string;
            profit_amount: string;
            /** Format: uuid */
            user_id: string;
        };
        /**
         * @description Supported exchange enum
         * @enum {string}
         */
        Exchange: "binance" | "okx" | "gate" | "bybit" | "huobi";
        /**
         * @description Counts returned by `on_trader_order` — useful for tests and the
         *     future metrics counter.
         */
        FanOutSummary: {
            /** Format: int32 */
            copied: number;
            /** Format: int32 */
            failed: number;
            /** Format: int32 */
            skipped_below_min: number;
            /** Format: int32 */
            skipped_risk: number;
        };
        /**
         * @description Wire shape for a feature flag row. The `db::feature_flag::Model` is
         *     the SeaORM-internal representation and uses a `Json` value for
         *     `user_whitelist` / `metadata`; this DTO is what the admin UI sees and
         *     what `openapi-typescript` consumes. All fields are camelCase on the
         *     wire (`#[serde(rename_all = "camelCase")]`).
         */
        FeatureFlag: {
            /**
             * Format: date-time
             * @description DB-side row insert timestamp.
             */
            createdAt: string;
            /** @description Free-text description shown in the admin UI. */
            description: string;
            /**
             * @description Global on/off switch. When `false`, no other column matters (other
             *     than whitelist overrides — see `services::feature_flag::evaluate_flag`).
             */
            enabled: boolean;
            /** @description Primary key, e.g. `"iceberg_order"`. VARCHAR(64) on the DB side. */
            key: string;
            /** @description Free-form JSON, e.g. `{"experiment": "v2"}`. Defaults to `{}`. */
            metadata: unknown;
            /**
             * Format: int32
             * @description 0..=100 — share of users (excluding whitelist) that see the feature.
             */
            percentageRollout: number;
            /**
             * Format: date-time
             * @description DB-side row update timestamp.
             */
            updatedAt: string;
            /**
             * Format: uuid
             * @description Admin user id (UUID) who last edited the row, if known.
             */
            updatedBy?: string | null;
            /**
             * @description JSON array of user UUIDs that always see the feature as on,
             *     regardless of `enabled` or `percentage_rollout`. Stored as JSONB.
             */
            userWhitelist: unknown;
        };
        /**
         * @description Response shape for the user bootstrap endpoint: a flat
         *     `{flag_key: bool}` map. The frontend renders UI affordances based on
         *     this map; unknown keys are absent (i.e. missing → treat as off).
         */
        FeatureFlagEvaluation: {
            /**
             * @description The `key` (string) of the flag. utoipa's `ToSchema` derive on a
             *     `HashMap<String, bool>` produces an open object with `additionalProperties:
             *     { type: boolean }`, which is exactly what the SPA expects.
             */
            flags: {
                [key: string]: boolean;
            };
        };
        /**
         * @description Subset of `pamm_funds` row surfaced via the API. Decimals are
         *     serialised as strings to preserve precision.
         */
        FundView: {
            base_currency: string;
            created_at: string;
            description?: string | null;
            high_water_mark: boolean;
            hwm: string;
            /** Format: uuid */
            id: string;
            management_fee_pct: string;
            /** Format: uuid */
            manager_id: string;
            manager_username?: string | null;
            name: string;
            nav: string;
            performance_fee_pct: string;
            share_value: string;
            status: string;
            /** Format: uuid */
            strategy_id?: string | null;
            total_shares: string;
            updated_at: string;
        };
        /** @description Per-user view of their investment, enriched with current value. */
        InvestmentView: {
            created_at: string;
            current_value: string;
            /** Format: uuid */
            fund_id: string;
            fund_name?: string | null;
            /** Format: uuid */
            id: string;
            initial_investment: string;
            share_pct: string;
            shares: string;
            unrealized_pnl: string;
            updated_at: string;
            /** Format: uuid */
            user_id: string;
        };
        InvestmentsResponse: {
            items: components["schemas"]["InvestmentView"][];
            /** Format: int64 */
            total: number;
        };
        ListFundsResponse: {
            items: components["schemas"]["FundView"][];
            /** Format: int64 */
            total: number;
        };
        ListTradersResponse: {
            items: components["schemas"]["TraderView"][];
            /** Format: int64 */
            total: number;
        };
        /** @description Liveness response payload. */
        LivenessResponse: {
            status: string;
            timestamp: string;
            version: string;
        };
        LoginRequest: {
            email?: string | null;
            password: string;
            username?: string | null;
        };
        LogoutResponse: {
            message: string;
        };
        MySubscriptionsResponse: {
            items: components["schemas"]["SubscriptionView"][];
            /** Format: int64 */
            total: number;
        };
        MyTraderResponse: {
            subscribers: components["schemas"]["SubscriptionView"][];
            /** Format: int64 */
            total_subscribers: number;
            trader?: null | components["schemas"]["TraderView"];
        };
        /**
         * @description (Renamed from `PammSubscribeRequest` to avoid clashing with
         *     `handlers::copy_trading::PammSubscribeRequest` after openapi-typescript
         *     7.x deduped the two. The wire format / JSON shape is unchanged —
         *     the tag `pamm` on the path operation identifies which schema the
         *     frontend should send.)
         */
        PammSubscribeRequest: {
            /** @description Amount in `fund.base_currency`. Decimal string. */
            amount: string;
        };
        /** @description Subset of `copy_profit_shares` row. */
        ProfitShareView: {
            distributed_at: string;
            follower_profit: string;
            /** Format: uuid */
            id: string;
            period_end: string;
            period_start: string;
            /** Format: uuid */
            subscription_id: string;
            trader_fee_pct: string;
            trader_profit: string;
        };
        ProfitSharesResponse: {
            items: components["schemas"]["ProfitShareView"][];
            /** Format: int64 */
            total: number;
        };
        /** @description Per-dependency check status. */
        ReadinessChecks: {
            database: string;
            redis: string;
        };
        /** @description Readiness response payload. */
        ReadinessResponse: {
            checks: components["schemas"]["ReadinessChecks"];
            status: string;
            timestamp: string;
            version: string;
        };
        RedeemRequest: {
            amount: string;
        };
        RedeemResponse: {
            amount_paid: string;
            /** Format: uuid */
            redemption_id: string;
            status: string;
        };
        RefreshTokenRequest: {
            refresh_token: string;
        };
        RegisterRequest: {
            bio?: string | null;
            display_name: string;
        };
        RegisterResponse: {
            trader: components["schemas"]["TraderView"];
        };
        RoleResponse: {
            /** Format: date-time */
            created_at: string;
            description?: string | null;
            display_name: string;
            /** Format: uuid */
            id: string;
            is_system: boolean;
            name: string;
        };
        SubscribeRequest: {
            /** @description Daily loss cap. 0 = no cap. */
            max_loss_per_day: string;
            /** @description Per-trade cap. 0 = no cap. */
            max_position_size: string;
            /** @description Copy ratio in (0, 1]. String to preserve precision. */
            ratio: string;
            /** Format: uuid */
            trader_id: string;
        };
        SubscribeResponse: {
            max_loss_per_day: string;
            max_position_size: string;
            ratio: string;
            status: string;
            /** Format: uuid */
            subscription_id: string;
        };
        /** @description Subset of `copy_subscriptions` row. */
        SubscriptionView: {
            ended_at?: string | null;
            /** Format: uuid */
            follower_id: string;
            /** Format: uuid */
            id: string;
            max_loss_per_day: string;
            max_position_size: string;
            ratio: string;
            started_at: string;
            status: string;
            /** Format: uuid */
            trader_id: string;
            trader_name?: string | null;
        };
        TickerResponse: {
            /** Format: double */
            ask: number;
            /** Format: double */
            bid: number;
            /** Format: double */
            change: number;
            /** Format: double */
            change_percent: number;
            /** Format: double */
            high: number;
            /** Format: double */
            low: number;
            /** Format: double */
            price: number;
            symbol: string;
            /** Format: int64 */
            timestamp: number;
            /** Format: double */
            volume: number;
        };
        TokenResponseBody: {
            access_token: string;
            /** Format: int64 */
            expires_in: number;
            refresh_token: string;
        };
        /** @description Subset of `copy_traders` row surfaced via the API. */
        TraderView: {
            bio?: string | null;
            created_at: string;
            display_name: string;
            /** Format: int64 */
            follower_count: number;
            /** Format: uuid */
            id: string;
            monthly_pnl: string;
            status: string;
            total_pnl: string;
            updated_at: string;
            /** Format: uuid */
            user_id: string;
            username?: string | null;
            win_rate: string;
        };
        TradesResponse: {
            items: components["schemas"]["CopyTradeView"][];
            /** Format: int64 */
            total: number;
        };
        UnsubscribeRequest: {
            /** Format: uuid */
            subscription_id: string;
        };
        UnsubscribeResponse: {
            status: string;
            /** Format: uuid */
            subscription_id: string;
        };
        /**
         * @description Request body for the admin upsert. Mirrors `entity::Model` but takes
         *     only the editable fields — the server fills in timestamps, and
         *     `updated_by` from the caller.
         */
        UpsertFeatureFlagRequest: {
            /**
             * @description Free-text description shown in the admin UI.
             * @example Iceberg order type (advanced parent/child)
             */
            description: string;
            /**
             * @description Global on/off switch. When `false`, no other column matters (other
             *     than whitelist overrides — see `services::feature_flag::evaluate_flag`).
             */
            enabled: boolean;
            /**
             * @description Primary key, e.g. `"iceberg_order"`. VARCHAR(64) on the DB side;
             *     the handler validates length before forwarding.
             * @example iceberg_order
             */
            key: string;
            /**
             * @description Free-form JSON, e.g. `{"experiment": "v2"}`. Defaults to `{}`
             *     when the admin doesn't supply one.
             */
            metadata?: unknown;
            /**
             * Format: int32
             * @description 0..=100 — share of users (excluding whitelist) that see the
             *     feature. Server-side clamped on read; we also clamp on write to
             *     keep the DB clean.
             * @example 25
             */
            percentage_rollout: number;
            /**
             * @description JSON array of user UUIDs that always see the feature as on,
             *     regardless of `enabled` or `percentage_rollout`. Stored as JSONB.
             */
            user_whitelist?: unknown;
        };
        UserMeResponse: components["schemas"]["UserResponse"];
        UserResponse: {
            avatar_url?: string | null;
            /** Format: date-time */
            created_at: string;
            display_name?: string | null;
            email: string;
            /** Format: uuid */
            id: string;
            is_active: boolean;
            /** Format: date-time */
            last_login_at?: string | null;
            role: components["schemas"]["RoleResponse"];
            username: string;
        };
        Value: unknown;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    feature_flags_admin_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All defined feature flag rows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Admin only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    feature_flags_admin_upsert: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertFeatureFlagRequest"];
            };
        };
        responses: {
            /** @description Persisted flag row */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureFlag"];
                };
            };
            /** @description Validation error (key length, whitelist shape, ...) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Admin only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    feature_flags_admin_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Flag primary key to delete */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Admin only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Flag with that key not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    audit_logs_list: {
        parameters: {
            query?: {
                /** @description Filter by actor user_id */
                user_id?: string;
                /** @description Filter by dotted action name (e.g. "user.role.changed") */
                action?: string;
                /** @description Filter by target_type */
                target_type?: string;
                /** @description Filter by target_id */
                target_id?: string;
                /** @description Filter by originating X-Request-Id */
                request_id?: string;
                /** @description created_at >= from */
                from?: string;
                /** @description created_at <= to */
                to?: string;
                /** @description 1-indexed page number */
                page?: number;
                /** @description Page size (1..=200) */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of audit log entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Admin only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    audit_logs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Audit log row id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Single audit log entry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogView"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Admin only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseBody"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current authenticated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMeResponse"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description Tokens refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponseBody"];
                };
            };
            /** @description Invalid or expired refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description User registered successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseBody"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Username or email already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    copy_trading_calculate_shares: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalculateSharesRequest"];
            };
        };
        responses: {
            /** @description Profit share calculated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculateSharesResponse"];
                };
            };
            /** @description Validation failed / no trades in period */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Already distributed for this period */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    copy_trading_my_subscriptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Caller's subscriptions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MySubscriptionsResponse"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    copy_trading_my_trader: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Caller's trader profile and subscribers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyTraderResponse"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    copy_trading_profit_shares: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Caller's profit-share history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfitSharesResponse"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    copy_trading_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Registered as a copy trader */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Already a copy trader */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    copy_trading_subscribe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscribeRequest"];
            };
        };
        responses: {
            /** @description Subscription created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscribeResponse"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Trader not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Already subscribed / trader not active */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    copy_trading_list_traders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of active copy traders */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListTradersResponse"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    copy_trading_get_trader: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trader id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trader detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraderView"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Trader not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    copy_trading_trades: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Caller's copied-trade audit */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradesResponse"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    copy_trading_unsubscribe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnsubscribeRequest"];
            };
        };
        responses: {
            /** @description Subscription cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnsubscribeResponse"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not the subscription owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Subscription not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    feature_flags_evaluate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Per-user boolean evaluation of every known flag */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureFlagEvaluation"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    system_readiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All dependencies healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description One or more dependencies down */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    market_get_depth: {
        parameters: {
            query: {
                /** @description Trading symbol (e.g. BTCUSDT) */
                symbol: string;
                /** @description Depth levels (5, 10, 20, 50) — default 10; 50 requires pro-trader/admin */
                levels?: number;
                /** @description Exchange to query (default: binance) */
                exchange?: components["schemas"]["Exchange"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order book depth */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepthResponse"];
                };
            };
            /** @description Invalid `levels` value */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Role not permitted for the requested depth */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    market_get_ticker: {
        parameters: {
            query?: {
                /** @description Trading symbol (e.g. BTCUSDT) */
                symbol?: string;
                /** @description Exchange to query (default: binance) */
                exchange?: components["schemas"]["Exchange"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ticker for the requested symbol */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TickerResponse"];
                };
            };
            /** @description Invalid symbol format */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Symbol not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    market_list_tickers: {
        parameters: {
            query?: {
                /** @description Optional symbol filter (e.g. BTCUSDT) */
                symbol?: string;
                /** @description Exchange to query (default: binance) */
                exchange?: components["schemas"]["Exchange"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of tickers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TickerResponse"][];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    pamm_list_funds: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of active funds */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListFundsResponse"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    pamm_create_fund: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFundRequest"];
            };
        };
        responses: {
            /** @description Fund created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateFundResponse"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    pamm_get_fund: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Fund id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fund detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundView"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Fund not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    pamm_distribute: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Fund id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DistributeRequest"];
            };
        };
        responses: {
            /** @description Distribution complete */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DistributeResponse"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not the fund manager */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Fund not active */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    pamm_list_fund_investments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Fund id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Investor list (manager + self) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestmentsResponse"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not the fund manager */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Fund not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    pamm_liquidate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Fund id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fund liquidated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not the fund manager */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    pamm_redeem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Fund id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedeemRequest"];
            };
        };
        responses: {
            /** @description Redemption accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RedeemResponse"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Fund not found / no investment */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    pamm_subscribe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Fund id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PammSubscribeRequest"];
            };
        };
        responses: {
            /** @description Subscription accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscribeResponse"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Fund not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Fund not active */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    pamm_my_investments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description My investments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestmentsResponse"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_get_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMeResponse"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_change_password: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangePasswordResponse"];
                };
            };
            /** @description Validation failed (e.g. old password wrong, new password too short) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_admin_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Target user id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUpdateUserRequest"];
            };
        };
        responses: {
            /** @description Updated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Admin only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    system_liveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponse"];
                };
            };
        };
    };
}
