/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /api/v1/audit-logs`
         * @description List audit log entries. All filters are optional and combine as AND.
         *     Pagination: `page` (1-indexed, default 1) / `size` (default 20, max 200).
         *
         *     Response shape: `ApiResponse<AuditLogPage>` where `AuditLogPage = { items, total, page, size }`.
         */
        get: operations["audit_logs_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit-logs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /api/v1/audit-logs/{id}`
         * @description Single audit entry by primary key. Returns 404 if not found.
         */
        get: operations["audit_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /api/v1/auth/login */
        post: operations["auth_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /api/v1/auth/logout */
        post: operations["auth_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/v1/auth/me - alias for /users/me */
        get: operations["auth_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /api/v1/auth/refresh */
        post: operations["auth_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /api/v1/auth/register */
        post: operations["auth_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe: DB 与 Redis 都可达时返回 200，否则 503。
         * @description 任何一个依赖 ping 失败就把整体标记为 unready。响应体里逐项列出结果，
         *     方便 dashboard / pagerDuty 看到具体哪个依赖挂了。
         */
        get: operations["system_readiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market/depth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/v1/market/depth — 获取深度数据 */
        get: operations["market_get_depth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market/ticker": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/v1/market/ticker — 获取单个交易对 Ticker */
        get: operations["market_get_ticker"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market/tickers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/v1/market/tickers — 获取所有交易对 Ticker */
        get: operations["market_list_tickers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user profile */
        get: operations["users_get_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change current user password */
        post: operations["users_change_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin: update user (including role) */
        post: operations["users_admin_update"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe: 进程在跑就返回 200。
         * @description 不检查任何外部依赖。即使下游 DB/Redis 全挂，liveness 仍应返回 OK，
         *     否则 k8s 会重启 Pod，而重启并不能恢复下游。
         */
        get: operations["system_liveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdminUpdateUserRequest: {
            avatar_url?: string | null;
            display_name?: string | null;
            email?: string | null;
            is_active?: boolean | null;
            /** Format: uuid */
            role_id?: string | null;
        };
        AuditLogView: {
            action: string;
            /** Format: date-time */
            created_at: string;
            diff: components["schemas"]["Value"];
            /** Format: uuid */
            id: string;
            ip_address: string;
            request_id?: string | null;
            target_id: string;
            target_type: string;
            user_agent?: string | null;
            /** Format: uuid */
            user_id?: string | null;
        };
        AuthResponseBody: {
            access_token: string;
            /** Format: int64 */
            expires_in: number;
            refresh_token: string;
            user: components["schemas"]["UserResponse"];
        };
        ChangePasswordRequest: {
            new_password: string;
            old_password: string;
        };
        ChangePasswordResponse: {
            message: string;
        };
        DepthLevel: {
            /** Format: double */
            price: number;
            /** Format: double */
            quantity: number;
            /** Format: double */
            total: number;
        };
        DepthResponse: {
            asks: components["schemas"]["DepthLevel"][];
            bids: components["schemas"]["DepthLevel"][];
            /** Format: int64 */
            timestamp: number;
        };
        /**
         * @description Supported exchange enum
         * @enum {string}
         */
        Exchange: "binance" | "okx" | "gate" | "bybit" | "huobi";
        /** @description Liveness response payload. */
        LivenessResponse: {
            status: string;
            timestamp: string;
            version: string;
        };
        LoginRequest: {
            email?: string | null;
            password: string;
            username?: string | null;
        };
        LogoutResponse: {
            message: string;
        };
        /** @description Per-dependency check status. */
        ReadinessChecks: {
            database: string;
            redis: string;
        };
        /** @description Readiness response payload. */
        ReadinessResponse: {
            checks: components["schemas"]["ReadinessChecks"];
            status: string;
            timestamp: string;
            version: string;
        };
        RefreshTokenRequest: {
            refresh_token: string;
        };
        RegisterRequest: {
            display_name?: string | null;
            email: string;
            password: string;
            username: string;
        };
        RoleResponse: {
            /** Format: date-time */
            created_at: string;
            description?: string | null;
            display_name: string;
            /** Format: uuid */
            id: string;
            is_system: boolean;
            name: string;
        };
        TickerResponse: {
            /** Format: double */
            ask: number;
            /** Format: double */
            bid: number;
            /** Format: double */
            change: number;
            /** Format: double */
            change_percent: number;
            /** Format: double */
            high: number;
            /** Format: double */
            low: number;
            /** Format: double */
            price: number;
            symbol: string;
            /** Format: int64 */
            timestamp: number;
            /** Format: double */
            volume: number;
        };
        TokenResponseBody: {
            access_token: string;
            /** Format: int64 */
            expires_in: number;
            refresh_token: string;
        };
        UserMeResponse: components["schemas"]["UserResponse"];
        UserResponse: {
            avatar_url?: string | null;
            /** Format: date-time */
            created_at: string;
            display_name?: string | null;
            email: string;
            /** Format: uuid */
            id: string;
            is_active: boolean;
            /** Format: date-time */
            last_login_at?: string | null;
            role: components["schemas"]["RoleResponse"];
            username: string;
        };
        Value: unknown;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    audit_logs_list: {
        parameters: {
            query?: {
                /** @description Filter by actor user_id */
                user_id?: string;
                /** @description Filter by dotted action name (e.g. "user.role.changed") */
                action?: string;
                /** @description Filter by target_type */
                target_type?: string;
                /** @description Filter by target_id */
                target_id?: string;
                /** @description Filter by originating X-Request-Id */
                request_id?: string;
                /** @description created_at >= from */
                from?: string;
                /** @description created_at <= to */
                to?: string;
                /** @description 1-indexed page number */
                page?: number;
                /** @description Page size (1..=200) */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of audit log entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Admin only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    audit_logs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Audit log row id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Single audit log entry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogView"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Admin only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseBody"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current authenticated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMeResponse"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description Tokens refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponseBody"];
                };
            };
            /** @description Invalid or expired refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description User registered successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseBody"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Username or email already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    system_readiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All dependencies healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description One or more dependencies down */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    market_get_depth: {
        parameters: {
            query: {
                /** @description Trading symbol (e.g. BTCUSDT) */
                symbol: string;
                /** @description Depth levels (5, 10, 20, 50) — default 10; 50 requires pro-trader/admin */
                levels?: number;
                /** @description Exchange to query (default: binance) */
                exchange?: components["schemas"]["Exchange"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order book depth */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepthResponse"];
                };
            };
            /** @description Invalid `levels` value */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Role not permitted for the requested depth */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    market_get_ticker: {
        parameters: {
            query?: {
                /** @description Trading symbol (e.g. BTCUSDT) */
                symbol?: string;
                /** @description Exchange to query (default: binance) */
                exchange?: components["schemas"]["Exchange"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ticker for the requested symbol */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TickerResponse"];
                };
            };
            /** @description Invalid symbol format */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Symbol not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    market_list_tickers: {
        parameters: {
            query?: {
                /** @description Optional symbol filter (e.g. BTCUSDT) */
                symbol?: string;
                /** @description Exchange to query (default: binance) */
                exchange?: components["schemas"]["Exchange"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of tickers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TickerResponse"][];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_get_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMeResponse"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_change_password: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangePasswordResponse"];
                };
            };
            /** @description Validation failed (e.g. old password wrong, new password too short) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_admin_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Target user id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUpdateUserRequest"];
            };
        };
        responses: {
            /** @description Updated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Unauthenticated */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Admin only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    system_liveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponse"];
                };
            };
        };
    };
}
