//! SeaORM Entity for `withdrawal_confirmations` table.
//!
//! PRD §3.18 — secure withdrawal flow with two-step confirmation:
//!   1. User submits a withdrawal request (amount, asset, destination).
//!   2. Server generates a 6-digit code, stores the **hash** of the code
//!      (never the plaintext), and pushes the plaintext code to the user
//!      via email / Telegram.
//!   3. User submits `{confirmation_id, code}` to /confirm. The server
//!      re-hashes the submitted code with SHA-256 and constant-time
//!      compares it against the stored hash; on match, status moves to
//!      `Confirmed` and a mock transfer is enqueued.
//!   4. Codes expire (default 15 minutes); `expire_overdue` is a 1-minute
//!      background worker that flips `status` to `Expired` for any `Pending`
//!      row past its `expires_at`.
//!
//! ## Why SHA-256, not bcrypt
//!
//! The code is 6 decimal digits → at most 10^6 candidates. Brute-forcing
//! bcrypt is the right thing for low-entropy *human-chosen* secrets; for
//! a uniformly random 6-digit code generated by `rand::thread_rng()`, SHA-256
//! is the same security level as the underlying secret (one-shot, server-issued)
//! and is dramatically faster. Each code lives for at most 15 minutes and is
//! single-use, so the brute-force window is also narrow.
//!
//! ## Columns
//!
//!   - `id`                — UUID v4 PK
//!   - `user_id`           — owner; rows are scoped per user for the GET /withdrawals endpoint
//!   - `amount`            — `Decimal(20,8)` to match the rest of the platform
//!   - `asset`             — VARCHAR(16) e.g. "USDT", "BTC"
//!   - `dest_address`      — VARCHAR(256) destination wallet / account
//!   - `confirm_code_hash` — VARCHAR(64) hex(SHA-256(code)) — see top of file
//!   - `expires_at`        — TIMESTAMPTZ, set to now + 15min on insert
//!   - `confirmed_at`      — TIMESTAMPTZ, set when status moves to Confirmed
//!   - `status`            — VARCHAR(16) one of {Pending, Confirmed, Expired, Cancelled}
//!                           (kept as VARCHAR rather than a Postgres enum so
//!                            adding a new state is a code change, not a migration)
//!   - `mock_withdrawal_id`— UUID set when status = Confirmed — the synthetic
//!                           transfer id we hand back to the user. No real
//!                           on-chain tx is sent (mock flow).
//!   - `created_at`        — TIMESTAMPTZ
//!
//! Indexes (see migration `m20260603130000_create_withdrawal_confirmations.sql`):
//!   - `(user_id, created_at DESC)`  — "this user's withdrawal history"
//!   - `(status, expires_at)`        — `expire_overdue` worker hot path
//!   - `(id)` is the PK so no extra index

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "withdrawal_confirmations")]
pub struct Model {
    /// UUID v4 PK. Avoiding BIGSERIAL to dodge hot-row contention on
    /// simultaneous confirmation requests.
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,

    /// Owner. All read paths must filter by `user_id` to prevent
    /// horizontal privilege escalation.
    pub user_id: Uuid,

    /// Amount in `asset` units. Decimal(20,8) matches the rest of the
    /// platform (orders, klines, etc.).
    #[sea_orm(column_type = "Decimal(Some((20, 8)))")]
    pub amount: Decimal,

    /// Asset ticker, e.g. "USDT", "BTC". VARCHAR(16) leaves room for
    /// "USDC.e" / "WETH" / future synthetic assets.
    #[sea_orm(column_type = "String(StringLen::N(16))")]
    pub asset: String,

    /// Destination wallet / account. VARCHAR(256) — fits an EVM address
    /// (42 chars) plus a leading memo / tag, with buffer for non-EVM chains
    /// (Bitcoin Cash legacy, etc.).
    #[sea_orm(column_type = "String(StringLen::N(256))")]
    pub dest_address: String,

    /// Lowercase hex of SHA-256(code). VARCHAR(64) = 32 bytes hex-encoded.
    /// Stored as a string (not `Vec<u8>`) to keep the DB column portable
    /// and to make the constant-time compare a string compare.
    #[sea_orm(column_type = "String(StringLen::N(64))")]
    pub confirm_code_hash: String,

    /// When the code stops being valid. Default = now + 15min on insert.
    /// Read by both `confirm` (reject if past) and the `expire_overdue`
    /// background worker (mark `Expired` and stop accepting the code).
    pub expires_at: DateTimeUtc,

    /// Set when status transitions Pending → Confirmed. NULL while
    /// Pending / Expired / Cancelled.
    pub confirmed_at: Option<DateTimeUtc>,

    /// Lifecycle state. VARCHAR(16) instead of a Postgres enum so we
    /// can add new states (e.g. `Failed`) without a migration.
    #[sea_orm(column_type = "String(StringLen::N(16))")]
    pub status: String,

    /// Set when status = Confirmed. Synthetic id we hand back to the
    /// user as `withdrawal_id`. NULL until then.
    pub mock_withdrawal_id: Option<Uuid>,

    pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

/// Well-known status values. Stored as plain strings (not a Postgres enum)
/// — adding a new state is a code change in this module, not a migration.
pub mod status {
    /// Code generated; awaiting user submission.
    pub const PENDING: &str = "Pending";
    /// User submitted correct code within the validity window.
    pub const CONFIRMED: &str = "Confirmed";
    /// Validity window passed before the user submitted a code.
    pub const EXPIRED: &str = "Expired";
    /// User / admin cancelled the request before it was confirmed.
    pub const CANCELLED: &str = "Cancelled";

    /// All known values; used by the worker / tests to detect typos.
    pub const ALL: &[&str] = &[PENDING, CONFIRMED, EXPIRED, CANCELLED];
}
