# .cargo/config.toml
[source.crates-io]
replace-with = 'bytedance'  # 中科大镜像

# 中科大镜像（sparse）
[source.ustc]
registry = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"

[source.bytedance]
registry = "sparse+https://rsproxy.cn/index/"
